### ISSUE TITLE
Instagram calendar

### ISSUE THREAD

**Issue by ettatottie** [WomenOfCryptoArt/website#20]
1) Offer artists the opportunity to take over Instagram for 1 or 2 weeks at a time
2) link posts to Twitter account 
3) link posts to Discord
4) arrange 'Instagram Live' streams

Ensure people use hashtags (e.g. #woca #hellowoca) and @hellowoca when posting

**Comment by SLRead** [comment]
Converted to project on project kanban: https://github.com/orgs/WomenOfCryptoArt/projects/1

**Comment by ettatottie** [comment]
Hi Sparrow,
We are all on a founders call. Are you available to join?
Etta


Sent from Yahoo Mail for iPhone


On Monday, April 12, 2021, 16:26, SRead ***@***.***> wrote:




Closed #20.
