### ISSUE TITLE
Metafest discussion panel

### ISSUE THREAD

**Issue by ettatottie** [WomenOfCryptoArt/website#21]
Topic - Inequalities in the ways men and women artists are perceived when creating evocative art.

1) Get 4 or 5 volunteers to be panel members 
2) Run through different points of view to ensure balanced arguments (keep it high level and avoid discussing specific incidents or speaking on behalf of any non-WOCA members)
3) Record the session and add subtitles if appropriate 

To be recorded between 7th-21st March

**Comment by SLRead** [comment]
This did not happen.
